In [4]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits= load_digits()

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [6]:
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)


# Logistic Regression

In [7]:
lr = LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(x_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

**SVM**

In [8]:
svc = SVC()
svc.fit(X_train,Y_train)
svc.score(x_test,y_test)

0.9916666666666667

**Random Forest**

In [9]:
rndm_forest = RandomForestClassifier()
rndm_forest.fit(X_train,Y_train)
rndm_forest.score(x_test,y_test) 

0.9777777777777777

In [10]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold()

In [15]:
score_logistic=[]
score_svm=[]
score_rf=[]

In [17]:
def modelScore(model,X_train,x_test,Y_train,y_test):
  model.fit(X_train,Y_train)
  return model.score(x_test,y_test)

In [24]:
for train_index,test_index in fold.split(digits.data,digits.target):
  X_train,x_test,Y_train,y_test =digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  score_rf.append(modelScore(RandomForestClassifier(n_estimators=20),X_train,x_test,Y_train,y_test))
  score_logistic.append(modelScore(LogisticRegression(),X_train,x_test,Y_train,y_test))
  score_svm.append(modelScore(SVC(),X_train,x_test,Y_train,y_test))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [21]:
score_logistic

[0.9194444444444444,
 0.8916666666666667,
 0.9526462395543176,
 0.9442896935933147,
 0.9192200557103064]

In [25]:
score_rf

[0.9194444444444444,
 0.9166666666666666,
 0.8777777777777778,
 0.947075208913649,
 0.958217270194986,
 0.8885793871866295]

In [26]:
score_svm

[0.9222222222222223,
 0.8694444444444445,
 0.9415041782729805,
 0.9387186629526463,
 0.8969359331476323,
 0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [27]:
from sklearn.model_selection import cross_val_score

In [28]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92153589, 0.94156928, 0.91652755])

In [29]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])