In [41]:
import pandas as pd
from sklearn.datasets import load_iris

In [42]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [43]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [44]:
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [45]:
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test = train_test_split(iris.data,df.target,test_size=0.25)

In [46]:
from sklearn.svm import SVC
svc = SVC()

In [47]:
svc.fit(X_train,Y_train)

SVC()

In [48]:
svc.score(x_test,y_test)

0.9736842105263158

In [49]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris.data,df.target,cv=3)

array([1.  , 0.94, 0.98])

In [50]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris.data,df.target,cv=3)

array([0.98, 0.98, 0.98])

In [51]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data,df.target,cv=4)

array([0.97368421, 0.92105263, 0.94594595, 1.        ])

In [52]:
import numpy as np
kernels=['linear','rbf']
c=[5,10,20]
avg_score={}
for i in kernels:
  for j in c:
    score =cross_val_score(SVC(kernel=i,C=j,gamma='auto'),iris.data,df.target,cv=5)
    avg_score[i+'_'+str(j)] = np.average(score)

avg_score


{'linear_5': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_5': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [53]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'),{
    'C':[10,20,30],
    'kernel':['linear','rbf']
},cv=5,return_train_score=False)
clf.fit(iris.data,df.target)
clf.cv_results_

{'mean_fit_time': array([0.00158896, 0.00115738, 0.00112138, 0.00122418, 0.00103111,
        0.0010942 ]),
 'std_fit_time': array([4.32321001e-04, 1.72945360e-05, 8.52208993e-05, 1.11983620e-04,
        1.69209346e-05, 1.95040970e-05]),
 'mean_score_time': array([0.0011692 , 0.00072818, 0.00070543, 0.0007895 , 0.00067177,
        0.00069561]),
 'std_score_time': array([6.17569327e-04, 1.32243030e-05, 2.65364912e-05, 1.35160550e-04,
        3.79856992e-06, 1.10278322e-05]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 

In [54]:
score_df = pd.DataFrame(clf.cv_results_)
score_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001589      0.000432         0.001169        0.000618      10   
1       0.001157      0.000017         0.000728        0.000013      10   
2       0.001121      0.000085         0.000705        0.000027      20   
3       0.001224      0.000112         0.000789        0.000135      20   
4       0.001031      0.000017         0.000672        0.000004      30   
5       0.001094      0.000020         0.000696        0.000011      30   

  param_kernel                         params  split0_test_score  \
0       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
1          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 30, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.900000           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.933333                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.900000                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                2  
1         0.980000        0.016330                1  
2         0.966667        0.042164                4  
3         0.966667        0.036515                3  
4         0.960000        0.048990                5  
5         0.960000        0.038873                5

In [55]:
score_df[['params','param_C','param_kernel']]


params param_C param_kernel
0  {'C': 10, 'kernel': 'linear'}      10       linear
1     {'C': 10, 'kernel': 'rbf'}      10          rbf
2  {'C': 20, 'kernel': 'linear'}      20       linear
3     {'C': 20, 'kernel': 'rbf'}      20          rbf
4  {'C': 30, 'kernel': 'linear'}      30       linear
5     {'C': 30, 'kernel': 'rbf'}      30          rbf

In [56]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [57]:
clf.best_score_

0.9800000000000001

In [58]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(SVC(),{
    'C':[10,20,30],
    'kernel':['linear','rbf']
},cv=5,return_train_score=False,n_iter=2)


In [59]:
clf.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=2,
                   param_distributions={'C': [10, 20, 30],
                                        'kernel': ['linear', 'rbf']})

In [60]:
clf.best_params_

{'kernel': 'rbf', 'C': 20}

In [61]:
clf.best_score_

0.9800000000000001

**Different model with different hyperparameter**

In [62]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [71]:
model_params={
    'svm':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[10,20,25],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
           'n_estimators': [1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [72]:
score=[]

for model_name,mp in model_params.items():
  clf = GridSearchCV(mp['model'],mp['params'],cv=2,return_train_score=False)
  clf.fit(iris.data,df.target)
  score.append({
      'model':model_name,
      'best_score':clf.best_score_,
      'best_params':clf.best_params_
  })

df = pd.DataFrame(score,columns=['model','best_score','best_params'])
df

model  best_score                    best_params
0                  svm    0.980000  {'C': 10, 'kernel': 'linear'}
1        random_forest    0.960000           {'n_estimators': 10}
2  logistic_regression    0.966667                      {'C': 10}